services:
  # Spring Boot Backend Web Service on Render Cloud
  - type: web
    name: bunk-management-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/sync/status
    envVars:
      - key: DATABASE_URL
        value: jdbc:postgresql://ep-royal-leaf-ax5uxvri-pooler.c-4.us-east-2.aws.neon.tech:5432/neondb?sslmode=require
      - key: DATABASE_USERNAME
        value: neondb_owner
      - key: DATABASE_PASSWORD
        value: npg_G3lmjgD2LJeb
      - key: DATABASE_DRIVER
        value: org.postgresql.Driver
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: FAST2SMS_API_KEY
        value: KfWMvE2Id76x1XAtjTQPsO9kUlriCHoJbc5a8Y4ezpn0NwRyGF9yNlarVRXWGDv6bKgmJ7sfCHhLTdAB
